name: Pre-release

on:
  push:
    tags:
      - 'v*.*.*-rc.*'

permissions:
  contents: write

jobs:
  prerelease:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.14.0

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Pre-release info
        run: echo "Pre-release workflow triggered for ${{ github.ref_name }}"
